### ISSUE TITLE
Unsure how to use

### ISSUE THREAD

**Issue by dhasial** [dark-beep-boop/base16-fuzzel#1]
I've got a prior base16 theme set up, but I've only just started fuzzel and I don't know how to use this repo to integrate the two. I'm reading the fuzzel manpage but it's very unclear how it would fit together with base16 at all.

**Comment by dark-beep-boop** [comment]
I use [flavours](https://github.com/Misterio77/flavours) to update the configuration files according to the current base16 theme. The following configuration works for fuzzel:
```
[[items]]
file = "~/.config/fuzzel/fuzzel.ini"
template = "fuzzel"
subtemplate = "smooth"
start = "### begin base16 scheme"
end = "### end base16 scheme"
rewrite = false
light = true
```

**Comment by dark-beep-boop** [comment]
Otherwise, you can check [base16](https://github.com/chriskempson/base16) documentation about [how to build](https://github.com/chriskempson/base16/blob/main/builder.md).

**Comment by dhasial** [comment]
Awesome, thanks for pointing me (and anyone else who might use this in the future) in the right direction.
